name: ct_seg_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.15
  - numpy>=1.24.0,<2.0.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - nibabel>=5.1.0
  - simpleitk>=2.3.0
  - opencv>=4.8.0
  - tqdm>=4.65.0